TRUNDLER_ORANGE = "#FB792B"
TRUNDLER_BLUE   = "#106682"
TRUNDLER_GREY   = "#AAAAAA"
TRUNDLER_GREEN  = "#5D9D3F"
TRUNDLER_RED    = "#EB284B"
TRUNDLER_SLATE  = "#708090"

usethis::use_data(
  TRUNDLER_ORANGE,
  TRUNDLER_BLUE,
  TRUNDLER_GREY,
  TRUNDLER_GREEN,
  TRUNDLER_RED,
  TRUNDLER_SLATE,
  internal = FALSE,
  overwrite = TRUE
)
